### ISSUE TITLE
Mention version of the Standard for Public Code the guide refers to

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/community-implementation-guide-standard#20]
Should we mention which version of the Standard for Public Code this guide currently is reflecting? If so, where?

**Comment by ericherman** [comment]
Yes, it would be good to mention that the version is currently aligned to 0.4.0 as well as the intent to update to the latest version shortly after the release.

And updating the community-implementation-guide-standard should be a post-release step added to the standard as well.

**Comment by ericherman** [comment]
fixed by 71f47a0b8901a5ac7cc2cee81d770ffca0274171
