### ISSUE TITLE
How does public code fit with existing EU laws?

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/community-implementation-guide-standard#50]
Code for NL meetup suggestion:
- provide reassurance/make transparent how specific standard criteria fit or comply with existing EU law (if need, break out by country)

**Comment by Ainali** [comment]
I have been thinking about this a bit, and I think it is very hard to do as it is a request to prove that it is not breaking any laws. Our ambition is, of course, that no criterion should break any law and that following the Standard should not have huge legal risks. Rather, I think that it would be possible to debunk a myth. So if there is any specific law that someone thinks conflicts with the Standard, we could guide around that. But until we have such a claim, I think it might be too big and too fuzzy task to solve this issue. Hence, I suggest that we close it and when there is more clarity, create issues related to identified and possibly problematic laws.

**Comment by Ainali** [comment]
Closing as no new comments have been made in 5 months since my suggestion to close it.
